# Generated by Django 4.2.1 on 2023-05-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
    ]
